# Generated by Django 2.2.13 on 2020-07-21 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoinwerken_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeequestion',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeequestion',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videoinwerken_manager.CourseQuestion'),
        ),
    ]
