# Generated by Django 2.2.13 on 2020-06-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_employee', models.BooleanField(default=False, verbose_name='is_employee')),
                ('is_manager', models.BooleanField(default=False, verbose_name='is_manager')),
                ('license_expiration_date', models.DateField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_address', models.CharField(blank=True, max_length=255, null=True)),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
