# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-15 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200613_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='expiration_date',
            new_name='license_expiration_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is_admin'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='is_employee'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='is_manager'),
        ),
    ]
