# Generated by Django 2.2.13 on 2020-07-07 20:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200624_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employees',
            field=models.ManyToManyField(related_name='employees10', to=settings.AUTH_USER_MODEL),
        ),
    ]
