# Generated by Django 2.2.13 on 2020-06-23 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0003_auto_20200615_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_user_id', to=settings.AUTH_USER_MODEL)),
                ('manager_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
