# Generated by Django 2.2.13 on 2020-06-24 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='employees',
            field=models.ManyToManyField(null=True, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
