# Generated by Django 2.2.13 on 2020-07-15 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoinwerken_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videoinwerken_manager.Course')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeQuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('course_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videoinwerken_manager.CourseQuestion')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('correct', models.BooleanField(default=False)),
                ('course_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='videoinwerken_manager.CourseQuestion')),
            ],
        ),
    ]
