# Generated by Django 2.2.13 on 2020-07-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoinwerken_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeQuizQuestion',
        ),
    ]
