# Generated by Django 2.2.13 on 2020-06-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoinwerken_manager', '0003_auto_20200615_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='manager',
            new_name='manager_id',
        ),
    ]
