# Generated by Django 2.2.13 on 2020-07-11 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employees',
        ),
        migrations.AddField(
            model_name='customuser',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='_customuser_employees_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
