# Generated by Django 2.2.13 on 2020-07-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200707_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='business_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='is_admin'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='is_employee'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='is_manager'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
