# Generated by Django 2.2.13 on 2020-07-07 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='_customuser_employees_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
