# Generated by Django 2.2.13 on 2020-07-09 19:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200707_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='employees',
            field=models.ManyToManyField(blank=True, related_name='_customuser_employees_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
