# Generated by Django 2.2.13 on 2020-07-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200709_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='license_expiration_date',
        ),
    ]
